# make environment
PYTHON = /usr/local/bin/python
ECHO = echo

# directories

# documentation source
DOCDIR = docs

# build directory
BUILDDIR = build

# built html documentation directory
HTMLDIR = html

# built pdf and zip documentation directory
DOCDEST = .

# name of template file for license
LICENSE_TEMPLATE = LICENSE-BSD.tmplt
